stages:
  - deploy

deploy_production:
  stage: deploy
  only:
    - main
  tags:
    - local
  script:
    # Tworzenie pliku .env z wartościami z GitLaba
    - echo -e "DB_NAME='$DB_NAME'\nDB_USER='$DB_USER'\nDB_PASSWORD='$DB_PASSWORD'\nDB_HOST='$DB_HOST'\nWP_ENV='production'\nWP_HOME='http://138.199.201.204'\nWP_SITEURL='http://138.199.201.204/wp'" > /var/www/honey-pearls-wordpress/.env

    # skopiuj repo do katalogu docelowego
    - rsync -av --exclude='.git' ./ /var/www/honey-pearls-wordpress/
    # wejdź do katalogu głównego Bedrock i zainstaluj zależności
    - cd /var/www/honey-pearls-wordpress/ && composer install --no-dev --optimize-autoloader

    # Zainstaluj zależności Composer w katalogu produkcyjnym
    - cd /var/www/honey-pearls-wordpress && composer install --no-dev --optimize-autoloader

  after_script:
    - echo "Deploy zakończony"