stages:
  - deploy
  - privileges

deploy_production:
  stage: deploy
  only:
    - main
  tags:
    - docker
  before_script:
    - apk add --no-cache rsync git unzip curl bash
    - chown -R www-data:www-data /var/www/honey-pearls-wordpress
  script:
    - cp "$ENV_FILE" /var/www/honey-pearls-wordpress/.env
    - chmod 644 /var/www/honey-pearls-wordpress/.env
    # skopiuj repo do katalogu docelowego
    - rsync -av --exclude='.git' ./ /var/www/honey-pearls-wordpress/
    # wejdź do katalogu głównego Bedrock i zainstaluj zależności
    - cd /var/www/honey-pearls-wordpress && composer install --no-dev --optimize-autoloader

  after_script:
    - echo "Deploy zakończony"

set_privileges:
  stage: privileges
  only:
    - main
  tags:
    - shell
  script:
    - chmod 644 /var/www/honey-pearls-wordpress/.env
    - find /var/www/honey-pearls-wordpress/web/wp-content -type d -exec chmod 755 {} \;
    - find /var/www/honey-pearls-wordpress/web/wp-content -type f -exec chmod 644 {} \;
  after_script:
    - echo "Zmiana uprawnień zakończona"